# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Greg/Capstone/digilent-xdc-master/Arty-S7-50-Master.xdc

# Block Designs: bd/InputMod/InputMod.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InputMod || ORIG_REF_NAME==InputMod} -quiet] -quiet

# IP: bd/InputMod/ip/InputMod_selectio_wiz_0_0/InputMod_selectio_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InputMod_selectio_wiz_0_0 || ORIG_REF_NAME==InputMod_selectio_wiz_0_0} -quiet] -quiet

# IP: bd/InputMod/ip/InputMod_xlconstant_0_0/InputMod_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InputMod_xlconstant_0_0 || ORIG_REF_NAME==InputMod_xlconstant_0_0} -quiet] -quiet

# IP: bd/InputMod/ip/InputMod_fifo_generator_0_0/InputMod_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InputMod_fifo_generator_0_0 || ORIG_REF_NAME==InputMod_fifo_generator_0_0} -quiet] -quiet

# IP: bd/InputMod/ip/InputMod_clk_wiz_0_0/InputMod_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==InputMod_clk_wiz_0_0 || ORIG_REF_NAME==InputMod_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/InputMod/InputMod_ooc.xdc
